apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-ntpserver
  labels:
    app: {{ .Release.Name }}-ntpserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-ntpserver
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-ntpserver
    spec:
      shareProcessNamespace: true
      containers:
      - envFrom:
        - configMapRef:
            name: {{ .Release.Name }}-ntpserver
        env:
        - name: http_proxy
          value: {{ .Values.http_proxy | quote }}
        - name: https_proxy
          value: {{ .Values.https_proxy | quote }}
        - name: no_proxy
          value: "{{ .Values.no_proxy }},influxdb2, ntpserv,smart-corridor-broker,smart-corridor-dlstreamer-pipeline-server,smart-corridor-grafana,smart-corridor-nodered,smart-corridor-pgserver,smart-corridor-scene,smart-corridor-web"
        image: {{ .Values.ntpserver.repository }}:{{ .Values.ntpserver.tag }}
        name: {{ .Release.Name }}-ntpserver
        imagePullPolicy: {{ .Values.imagePullPolicy }}
        ports:
          - containerPort: 123
      restartPolicy: Always
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
